global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.IdentityModel.Tokens;
global using System.Text;
global using Task_Test.DataContext;
global using Task_Test.DataContext.Models.User;
global using Task_Test.Options.Config;
global using FluentValidation.AspNetCore;
global using Mediator;